name: cooking_book
description: A Flutter app displaying recipes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true   # <--- MUST BE PRESENT FOR FLUTTER GEN-L10N
  assets:
    - assets/recipes.json
